[package]
name = "serendipity"
version = "0.1.0"
edition = "2021"
authors = ["Merlin <Merlin#7667>"]
description = "A discord bot by Merlin"
build = "build.rs"

[dependencies]
dotenv = "0.15.0"
#serenity = { version = "0.11", default-features = false, features = ["builder","cache","client","gateway","http","model","utils","rustls_backend"] }
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
uptime_lib = "0.2.2"
built = { version = "0.5", features = ["chrono", "semver"] }
sysinfo = "0.26.7"
env_logger = "0.10.0"
log = "0.4"
serenity = {version = "0.11.5", default-features = false, features = ["builder","cache","client","gateway","http","model","utils","rustls_backend"] }
poise = "0.5.0"
songbird = "0.3.0"
symphonia = "0.5.1"


[build-dependencies]
built = { version = "0.5", features = ["git2", "chrono", "semver"] }