[package]
name = "serendipity"
version = "0.1.0"
edition = "2021"
authors = ["Merlin <Merlin#7667>"]
description = "A discord bot by Merlin"
build = "build.rs"

[dependencies]
dotenv = "0.15.0"
#serenity = { version = "0.11", default-features = false, features = ["builder","cache","client","gateway","http","model","utils","rustls_backend"] }
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
uptime_lib = "0.2.2"
built = { version = "0.5", features = ["chrono", "semver"] }
sysinfo = "0.27.1"
env_logger = "0.10.0"
log = "0.4"
#poise = { git = "https://github.com/serenity-rs/poise", branch = "serenity-next"}
poise = { path = "./dependencies/poise-0.5.2" }
reqwest = "0.11"
regex = "1.7.0"
is-url = "1.0.4"
rand = "0.8.5"
lazy_static = "1.4.0"
itertools = "0.10.5"
ms-converter = "1.4.0"

# [dependencies.serenity]
# git = "https://github.com/serenity-rs/serenity?rev=ea134e2a1b947c5a56538b7faa29156e367c6d21"
# #rev = "ea134e2a1b947c5a56538b7faa29156e367c6d21"
# features = ["builder","cache","client","gateway","http","model","utils","rustls_backend"]

# Including songbird alone gives you support for Opus via the DCA file format.
[dependencies.songbird]
path = "./dependencies/songbird-next"
#git = "https://github.com/serenity-rs/songbird"
#branch = "next"
features = ["builtin-queue"]

# To get additional codecs, you *must* add Symphonia yourself.
# This includes the default formats (MKV/WebM, Ogg, Wave) and codecs (FLAC, PCM, Vorbis)...
[dependencies.symphonia]
# version = "0.5"
features = ["aac", "mp3", "isomp4", "alac"] # ...as well as any extras you need!
# **NOTE**: For now, please use this repository in pre-releases.
git = "https://github.com/pdeljanov/Symphonia"

[build-dependencies]
built = { version = "0.5", features = ["git2", "chrono", "semver"] }

[patch.crates-io]
serenity = { path = "./dependencies/serenity-0.11.5"}
#serenity = { git = "https://github.com/serenity-rs/serenity?rev=ea134e2a1b947c5a56538b7faa29156e367c6d21"}

#[patch."https://github.com/serenity-rs/serenity"]
#serenity = { git = "https://github.com/serenity-rs/serenity?rev=ea134e2a1b947c5a56538b7faa29156e367c6d21"}

[patch."https://github.com/serenity-rs/serenity"]
serenity = { path = "./dependencies/serenity-0.11.5"}
#serenity = "0.11.5"