[package]
name = "serendipity"
version = "0.1.0"
edition = "2021"
authors = ["Merlin <Merlin#7667>", "Ekpy <Ekpy#1372>"]
description = "A discord bot by Ekpy & Merlin"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
serenity = { version = "0.11", default-features = false, features = ["builder","cache","client","gateway","http","model","utils","rustls_backend"] }
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
poise = "0.4.1"
uptime_lib = "0.2.2"
built = { version = "0.5", features = ["chrono", "semver"] }
sysinfo = "0.26.7"

[build-dependencies]
built = { version = "0.5", features = ["git2", "chrono", "semver"] }